### ISSUE TITLE
The project page is inaccessible...

### ISSUE THREAD

**Issue by zhimin-z** [Exploration-Lab/BookSQL#4]
Check this link
![image](https://github.com/user-attachments/assets/379f329f-0e39-44d9-be28-cb8c6f7d12f9)
but found:
<img width="973" alt="image" src="https://github.com/user-attachments/assets/e8bd0498-0e6d-4653-a060-bb18aadbd453">

**Comment by Exploration-Lab** [comment]
Thanks for pointing out the typo on Hugging Face, we will fix it, here is the correct link: https://github.com/Exploration-Lab/BookSQL

**Comment by Exploration-Lab** [comment]
Thanks for pointing out the typo on Hugging Face, we will fix it, here is the correct link: https://github.com/Exploration-Lab/BookSQL
