### ISSUE TITLE
The submission template is unavailable...

### ISSUE THREAD

**Issue by zhimin-z** [Exploration-Lab/BookSQL#5]
Check this link
![image](https://github.com/user-attachments/assets/1e2e4a5d-f30e-4d9e-8709-4c83a2e0ffe2)
but found:
<img width="855" alt="image" src="https://github.com/user-attachments/assets/e7c2f84c-aae3-4d23-9fac-87f9a1ad563e">

**Comment by Exploration-Lab** [comment]
Thanks for pointing out the typo, here is the correct link: https://huggingface.co/spaces/Exploration-Lab/BookSQL-Leaderboard/blob/main/sample_prediction.csv
